### ISSUE TITLE
SPGW-C: endless loop "handle_receive exception GTPV2-C msg 0 Bad Length 1024 Exception"

### ISSUE THREAD

**Issue by dreibh** [OPENAIRINTERFACE/openair-cn-cups#25]
Hi,

my SPGW-C instances sometimes go into an endless loop:
...
[2020-08-24T11:15:40.173726] [spgwc] [sgwc_s5  ] [info ] handle_receive exception GTPV2-C msg 0 Bad Length 1024 Exception
[2020-08-24T11:15:43.923771] [spgwc] [gtpv2_c  ] [error] GTP IE type 0 length 0
[2020-08-24T11:15:43.923931] [spgwc] [sgwc_s5  ] [info ] handle_receive exception GTPV2-C msg 0 Bad Length 1024 Exception
[2020-08-24T11:15:43.923997] [spgwc] [gtpv2_c  ] [error] GTP IE type 0 length 0
[2020-08-24T11:15:43.924042] [spgwc] [sgwc_s5  ] [info ] handle_receive exception GTPV2-C msg 0 Bad Length 1024 Exception
[2020-08-24T11:15:43.924070] [spgwc] [gtpv2_c  ] [error] GTP IE type 0 length 0
[2020-08-24T11:15:43.924107] [spgwc] [sgwc_s5  ] [info ] handle_receive exception GTPV2-C msg 0 Bad Length 1024 Exception
[2020-08-24T11:15:43.924132] [spgwc] [gtpv2_c  ] [error] GTP IE type 0 length 0
...

Git repository: https://github.com/OPENAIRINTERFACE/openair-cn-cups.git
Git tag: "2019.w47"

When the issue occurs, I tried to stop all components (i.e. HSS, MME, SPGW-C and SPGW-U) and only start the SPGW-C again. Then, it still occurs. So, it seems that the state is persistent once it has occurred.

**Comment by lionelgo** [comment]
Hello,

You may check if there is not already an instance running, or a 
network/interface problem.

Regards,

Lionel Gauthier

**Comment by dreibh** [comment]
Yes, this seems to be the issue. My dummy interfaces dummy0:s5c and dummy0:p5c for S5S8 had been removed. So, after adding the dummy interfaces again, the SPGW-C is okay.

However, the SPGW-C should not go into an endless loop in this error case (i.e. missing dummy interfaces for S5S8). So, I am leaving this issue open.

**Comment by dreibh** [comment]
Some debugging:
gtpc_msg_bad_length_exception() is causing the error message. It is called from src/gtpv2c/3gpp_29.274.hpp by gtpv2c_msg::load_from().

Replacing the generated exception by abort(), I generated the following stack trace:
```
...
[2020-08-24T12:43:45.322884] [spgwc] [gtpv2_c  ] [error] GTP IE type 0 length 0
[New Thread 0x7fffec8f4700 (LWP 11598)]

Thread 11 "spgwc" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffed8f6700 (LWP 11596)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff56af8b1 in __GI_abort () at abort.c:79
#2  0x0000555555a2a035 in gtpv2c::gtpv2c_msg::load_from (this=0x7fffed8f58f0, is=...) at /home/nornetpp/src/openair-cn-cups/src/gtpv2c/3gpp_29.274.hpp:482
#3  0x0000555555a36af7 in sgwc::sgw_s5s8::handle_receive (this=0x629000014200, recv_buffer=0x629000014228 '\276' <repeats 200 times>..., bytes_transferred=18446744073709551615, remote_endpoint=...)
    at /home/nornetpp/src/openair-cn-cups/src/sgwc/sgwc_s5s8.cpp:386
#4  0x0000555555b83106 in udp_server::udp_read_loop (this=0x629000014210, sched_params=...) at /home/nornetpp/src/openair-cn-cups/src/udp/udp.cpp:72
#5  0x0000555555b88010 in std::__invoke_impl<void, void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> (__f=
    @0x604000085530: (void (udp_server::*)(udp_server * const, const util::thread_sched_params &)) 0x555555b82ed6 <udp_server::udp_read_loop(util::thread_sched_params const&)>, __t=@0x604000085528: 0x629000014210)
    at /usr/include/c++/7/bits/invoke.h:73
#6  0x0000555555b876d3 in std::__invoke<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> (__fn=
    @0x604000085530: (void (udp_server::*)(udp_server * const, const util::thread_sched_params &)) 0x555555b82ed6 <udp_server::udp_read_loop(util::thread_sched_params const&)>) at /usr/include/c++/7/bits/invoke.h:95
#7  0x0000555555b889b7 in std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> >::_M_invoke<0ul, 1ul, 2ul> (this=0x604000085518)
    at /usr/include/c++/7/thread:234
#8  0x0000555555b88926 in std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> >::operator() (this=0x604000085518) at /usr/include/c++/7/thread:243
#9  0x0000555555b888e3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> > >::_M_run (this=0x604000085510)
    at /usr/include/c++/7/thread:186
#10 0x00007ffff60d36df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007ffff65bc6db in start_thread (arg=0x7fffed8f6700) at pthread_create.c:463
#12 0x00007ffff5790a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) where full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 0, 0, 0, 0, 0, 0, 140737321706491, 0, 15311397460501508352, 140737178982240, 15311397460501508352, 140737178982144, 140737178982240, 140737178981856, 140737178982240}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff56af8b1 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fffed8f5770, sa_sigaction = 0x7fffed8f5770}, sa_mask = {__val = {93824997295024, 1102416563, 93825000708224, 93824998743544, 93825000421839, 93825004035952, 18446744073709547520, 
              140737264619520, 140737343463096, 17592147372792, 140737336336439, 6, 140737178976256, 0, 140737178982496, 140737178982336}}, sa_flags = -134041344, sa_restorer = 0x7fffed8f5860}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x0000555555a2a035 in gtpv2c::gtpv2c_msg::load_from (this=0x7fffed8f58f0, is=...) at /home/nornetpp/src/openair-cn-cups/src/gtpv2c/3gpp_29.274.hpp:482
        check_msg_length = 1020
        ie = 0x0
        ies_length = 0
#3  0x0000555555a36af7 in sgwc::sgw_s5s8::handle_receive (this=0x629000014200, recv_buffer=0x629000014228 '\276' <repeats 200 times>..., bytes_transferred=18446744073709551615, remote_endpoint=...)
    at /home/nornetpp/src/openair-cn-cups/src/sgwc/sgwc_s5s8.cpp:386
        iss = <incomplete type>
        msg = {<gtpv2c::gtpv2c_msg_header> = {<stream_serializable> = {_vptr.stream_serializable = 0x555556073f18 <vtable for gtpv2c::gtpv2c_msg+16>}, u1 = {bf = {spare = 0 '\000', mp = 0 '\000', t = 0 '\000', p = 0 '\000', 
                version = 2 '\002'}, b = 64 '@'}, message_type = 0 '\000', message_length = 1024, teid = 0, sequence_number = 12636217, u2 = {bf = {spare = 0 '\000', message_priority = 0 '\000'}, b = 0 '\000'}}, remote_port = 0, 
          ies = std::vector of length 0, capacity 0}
#4  0x0000555555b83106 in udp_server::udp_read_loop (this=0x629000014210, sched_params=...) at /home/nornetpp/src/openair-cn-cups/src/udp/udp.cpp:72
        r_endpoint = {addr_storage = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, addr_storage_len = 128}
        bytes_received = 18446744073709551615
#5  0x0000555555b88010 in std::__invoke_impl<void, void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> (__f=
    @0x604000085530: (void (udp_server::*)(udp_server * const, const util::thread_sched_params &)) 0x555555b82ed6 <udp_server::udp_read_loop(util::thread_sched_params const&)>, __t=@0x604000085528: 0x629000014210)
    at /usr/include/c++/7/bits/invoke.h:73
No locals.
#6  0x0000555555b876d3 in std::__invoke<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> (__fn=
    @0x604000085530: (void (udp_server::*)(udp_server * const, const util::thread_sched_params &)) 0x555555b82ed6 <udp_server::udp_read_loop(util::thread_sched_params const&)>) at /usr/include/c++/7/bits/invoke.h:95
No locals.
#7  0x0000555555b889b7 in std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> >::_M_invoke<0ul, 1ul, 2ul> (this=0x604000085518)
    at /usr/include/c++/7/thread:234
No locals.
#8  0x0000555555b88926 in std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> >::operator() (this=0x604000085518) at /usr/include/c++/7/thread:243
No locals.
#9  0x0000555555b888e3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (udp_server::*)(util::thread_sched_params const&), udp_server*, util::thread_sched_params> > >::_M_run (this=0x604000085510)
    at /usr/include/c++/7/thread:186
No locals.
#10 0x00007ffff60d36df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#11 0x00007ffff65bc6db in start_thread (arg=0x7fffed8f6700) at pthread_create.c:463
        pd = 0x7fffed8f6700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737178986240, 2979406252378743846, 140737178984128, 0, 140737488343376, 140737488343200, -2979376147858660314, -2979387867998395354}, mask_was_saved = 0}}, priv = {pad = {0x0, 
              0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#12 0x00007ffff5790a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```
